### ISSUE TITLE
Web UI hangs forever on 100% upload after an upload

### ISSUE THREAD

**Issue by NachtaktiverHalbaffe** [Sebclem/hassio-nextcloud-backup#100]
**Describe the bug**
In the step after downloading the snapshot from HA it does sucessfully upload the backup to my nextcloud and says the upload is complete in the logs (and its complete if I check on my NC instance), but in the web ui it hangs on 100% forever and wont do manual/automatic backups anymore.  In version 0.16.3 everything worked fine, so I think it could be a bug and not something with my Nextcloud instance.

Logs:
````
[2021-12-22 18:53:59] [info]: 	Satus : Go !
[2021-12-22 18:53:59] [info]: 	Initializing and checking webdav client...
[2021-12-22 18:53:59] [info]: 	Starting auto clean cron...
[2021-12-22 18:53:59] [info]: 	Starting Cron...
[2021-12-22 18:53:59] [info]: 	Hassio API : Go !
[2021-12-22 18:54:03] [info]: 	Nextcloud connection : Go !
[2021-12-23 01:00:00] [info]: 	Local clean done.
[2021-12-23 01:00:01] [info]: 	Cloud clean done.
[2021-12-23 05:00:00] [info]: 	Stopping addons...
[2021-12-23 05:00:00] [info]: 	... Ok
[2021-12-23 05:00:00] [info]: 	Creating new snapshot...
[2021-12-23 05:04:10] [info]: 	Snapshot created with id XXXXXXXXX
[2021-12-23 05:04:10] [info]: 	Downloading snapshot XXXXXXXX...
[2021-12-23 05:04:28] [info]: 	Download success !
[2021-12-23 05:04:28] [info]: 	Uploading snap...
[2021-12-23 05:31:34] [info]: 	Upload done...
[2021-12-24 01:00:00] [info]: 	Local clean done.
[2021-12-24 01:00:01] [info]: 	Cloud clean done.
[2021-12-25 01:00:00] [info]: 	Local clean done.
[2021-12-25 01:00:01] [info]: 	Cloud clean done.
````

**To Reproduce**
Doing any manual/automatic Backup. Bug appears both in manual and automatic backups.

**Expected behavior**
After uploading finishes displaying "done" (don't know the exact label) and waiting for next manual/automatic backup

**System information**
- Home Assistant Version : 2021.12.4
- Home Assistant Supervisor Version : 2021.12.4
- Nextcloud Version : 22.2.3 (Snap)
- Addon version : 0.16.4
- If any, reverse proxy in fort on Nextcloud :  nginx via nginx proxy manager

**Additional context**
Screenshot of web ui when bug appeared: 
![Screenshot 2022-01-03 151532](https://user-images.githubusercontent.com/57433516/147940879-fa85936e-f14d-4305-9713-390f3dff206a.jpg)

**Comment by Sebclem** [comment]
This should be fixed with the last update (0.17.2), can you confirm ?

**Comment by MEfinger** [comment]
I just updated and tried a manual and automatic backup but I have the problem still. 
Log below:
```
Add-on: Nextcloud Backup
Easily upload your Home Assistant backups to Nextcloud
-----------------------------------------------------------
Add-on version: 0.17.2
You are running the latest version of this add-on.
System: Home Assistant OS 7.6  (amd64 / qemux86-64)
Home Assistant Core: 2022.4.7
Home Assistant Supervisor: 2022.04.0
-----------------------------------------------------------
Please, share the above information when looking for help
or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
Log level is set to INFO
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[16:24:48] INFO: Starting Node...
[2022-05-02 16:24:49] [info]: 	Log level: info
[2022-05-02 16:24:49] [info]: 	Backup timeout: 5400000
[2022-05-02 16:24:49] [info]: 	Satus : Go !
[2022-05-02 16:24:49] [info]: 	Initializing and checking webdav client...
[2022-05-02 16:24:49] [info]: 	Starting auto clean cron...
[2022-05-02 16:24:49] [info]: 	Starting Cron...
[2022-05-02 16:24:49] [info]: 	Hassio API : Go !
[2022-05-02 16:24:50] [info]: 	Nextcloud connection : Go !
[2022-05-02 16:25:07] [info]: 	Stopping Cron...
[2022-05-02 16:25:07] [info]: 	Starting Cron...
[2022-05-02 16:30:00] [info]: 	Stopping addons...
[2022-05-02 16:30:00] [info]: 	... Ok
[2022-05-02 16:30:00] [info]: 	Creating new snapshot...
[2022-05-02 16:47:18] [info]: 	Snapshot created with id 3c4b3d25
[2022-05-02 16:47:18] [info]: 	Downloading snapshot 3c4b3d25...
[2022-05-02 16:47:29] [info]: 	Download success !
[2022-05-02 16:47:29] [info]: 	Uploading snap...
[2022-05-02 17:02:01] [info]: 	Upload done...
```

Its still at the 100% right now.

**Comment by Sebclem** [comment]
Did you have any error in the Chrome dev tools ? (F12 in Chrome and Firefox)

**Comment by MEfinger** [comment]
Since some days it works again. But I cant say if it was for the update or if the problem came from my own stupidity. Both my Nextcloud and Home Assistant were running multiple Backup Tasks in the time between 2 and 5 in the morning. Since I changed the time to 4 in the afternoon the backups work again nicely.
